// Championship Run — i18n language pack (EN + ZH)
// Player names, team names, position/stat abbreviations stay in English.

const LANG = {
  en: {
    // ---- Header ----
    'brand.title': 'Championship Run',
    'brand.tagline': 'NBA Roster-Building Simulation',
    'nav.home': 'Home',

    // ---- Home: quick-action cards ----
    'home.newRun': 'Start a New Run',
    'home.newRun.desc': 'Pick your team, build a roster, compete for a championship.',
    'home.save': 'Save & Backup',
    'home.save.desc': 'Export, import, or switch sessions.',
    'home.library': 'Player Library',
    'home.library.desc': 'Search and sort all players by rating, stats, or position.',
    'home.matchup': 'Simulate Matchup',
    'home.matchup.desc': 'Build two teams and simulate head-to-head.',
    'home.trophy': '🏆 Trophy Room',
    'home.hof': '🏅 Hall of Fame',
    'home.manageSaves': 'Manage saves…',
    'home.continue': 'Continue Last Run',
    'home.continueBtn': 'Continue',

    // ---- New Run form ----
    'form.gameMode': 'Game mode',
    'form.normal': 'Normal',
    'form.normalHint': '(2025-26 season)',
    'form.dynasty': 'Dynasty',
    'form.dynastyHint': '(up to 10 seasons)',
    'form.teamName': 'Your team name',
    'form.teamNameHint': '(optional)',
    'form.teamName.placeholder': 'e.g. The Rebuilders',
    'form.replaceTeam': 'Replace a team (picks your conference)',
    'form.draftMode': 'Draft mode',
    'form.open': 'Open',
    'form.blind': 'Blind',
    'form.difficulty': 'Difficulty',
    'form.normalDiff': 'Normal',
    'form.hard': 'Hard',
    'form.hardHint': '($400M salary cap)',
    'form.startDraft': 'Start Draft',
    'form.archive': 'Season Archive',

    // ---- Progress bar ----
    'step.draft': 'Draft',
    'step.lineup': 'Lineup',
    'step.season': 'Season',
    'step.playoffs': 'Playoffs',
    'step.result': 'Result',

    // ---- Draft ----
    'draft.title': 'Draft',
    'draft.rookieTitle': 'Rookie Draft',
    'draft.desc': 'Pick 1 of 5 players each round, until you have 10.',
    'draft.reroll': 'Re-roll',
    'draft.picked': 'picked',
    'draft.need': 'Need',
    'draft.pick': 'Pick',
    'draft.bigBoard': 'Draft Board',
    'draft.yourPick': 'You pick at',
    'draft.picksSoFar': 'Draft so far',
    'draft.pass': 'Pass (skip pick)',

    // ---- Free Agency ----
    'fa.title': 'Offseason Free Agency',
    'fa.desc': 'Release a player to free a spot, then sign a free agent. Or skip straight to your lineup.',
    'fa.done': 'Done — Go to Lineup',
    'fa.release': 'Release',
    'fa.sign': 'Sign',
    'fa.contract': 'Contract',
    'fa.years': 'yr',
    'fa.salary': 'Salary',
    'fa.needs': 'Needs',
    'fa.refresh': 'Refresh market',
    'fa.signings': 'Signings',

    // ---- Lineup ----
    'lineup.title': 'Set Your Starting 5',
    'lineup.desc': 'Assign one player per position. Out-of-position players take a rating penalty.',
    'lineup.strength': 'Team Strength',
    'lineup.updates': 'updates as you change starters',
    'lineup.confirm': 'Confirm Lineup',

    // ---- Season ----
    'season.title': 'Regular Season',
    'season.simulate': 'Simulate 82-Game Season',
    'season.midseason': 'Mid-season break',
    'season.midseasonHelp': 'You can now adjust your lineup, make trades, then simulate the second half.',
    'season.adjustLineup': '🎯 Adjust lineup',
    'season.tradeWindow': '🔄 Trade window',
    'season.simulateSecond': '▶ Simulate 2nd half',
    'season.averages': 'Your team\'s 82-game averages',
    'season.firstHalf': 'First-half averages',
    'season.afterGames': 'after',
    'season.form': 'Season Form',
    'season.awards': 'Regular Season Awards',
    'season.mvp': '🏆 MVP',
    'season.dpoy': '🛡️ Defensive Player',
    'season.sixthMan': '🔥 Sixth Man',
    'season.allNba': '🌟 All-NBA First Team',
    'season.missedPlayoffs': 'You missed the playoffs.',
    'season.backHome': 'Back to Home',
    'season.toPlayoffs': 'Continue to Playoffs',

    // ---- Trade ----
    'trade.pointsRemaining': 'trade points remaining',
    'trade.pointsThis': 'this season',
    'trade.rules': 'Rules: 1-for-1 costs 1 · 2-for-2 costs 2 · 3-for-3 costs 3. 3 points per season.',
    'trade.propose': 'Propose',
    'trade.shop': 'Shop my players',
    'trade.incoming': 'Incoming offers',
    'trade.yourPlayers': 'Your players (1-3)',
    'trade.pickSame': 'players (pick same count)',
    'trade.proposeBtn': 'Propose trade',
    'trade.shopBtn': 'Get offers',
    'trade.acceptBtn': 'Accept',
    'trade.pickPlayers': 'Shop these players (1-3)',
    'trade.leagueLog': 'League trade log',
    'trade.accepted': 'Trade accepted',
    'trade.rejected': 'Trade rejected',
    'trade.needSame': 'Pick the same number (1-3) on both sides.',

    // ---- Playoffs ----
    'playoffs.title': 'Playoffs',
    'playoffs.settingUp': 'Setting up the bracket…',
    'playoffs.bracket': 'Playoff Bracket',
    'playoffs.round': 'Round',
    'playoffs.simulateRound': 'Simulate Round',
    'playoffs.roundResult': 'Results',
    'playoffs.def': 'def.',
    'playoffs.youWon': 'YOU WON',
    'playoffs.youLost': 'you lost',
    'playoffs.mvp': '🏅 Series MVP',
    'playoffs.seriesRosters': 'Team rosters (10 each)',
    'playoffs.playerAverages': 'Player averages (series)',
    'playoffs.wonChampionship': 'won the championship!',
    'playoffs.seeResult': 'See Result',
    'playoffs.eliminated': 'You were eliminated in round',
    'playoffs.eliminatedEnd': '. The playoffs continue without you.',

    // ---- Result ----
    'result.title': 'Season Result',
    'result.champions': 'CHAMPIONS!',
    'result.eliminated': 'Eliminated in round',
    'result.eliminatedRound': '',
    'result.wonTitle': 'won the NBA Finals.',
    'result.dynastyMaterial': 'Dynasty material.',
    'result.rebuild': 'Your run ended. Rebuild and try again.',
    'result.otherChampOther': 'won the championship',
    'result.championships': 'Championships',
    'result.awardsWon': 'Awards won',
    'result.starters': 'Starters',
    'result.bench': 'Bench',
    'result.topScorers': 'Top scorers',
    'result.teamLeaders': 'Team leaders',
    'result.nextSeason': 'Next Season',
    'result.dynastyComplete': '🏆 Dynasty complete —',
    'result.seasons': 'seasons played.',
    'result.printSummary': '🖨️ Save / Print Summary',
    'result.backHome': 'Back to Home',
    'result.dynastyHistory': 'Dynasty History',

    // ---- History ----
    'history.season': 'Season',
    'history.record': 'Record',
    'history.champion': 'Champion',
    'history.mvp': 'MVP',
    'history.result': 'Result',
    'history.championLabel': '🏆 Champion',
    'history.missedPlayoffs': 'Missed playoffs',
    'history.eliminated': 'Eliminated R',
    'history.playoffs': 'Playoffs',

    // ---- Recap ----
    'recap.title': 'Offseason Recap',
    'recap.continue': 'Continue',
    'recap.champion': '🏆 Champion',
    'recap.mvp': '🌟 Regular-season MVP',
    'recap.retired': 'Retired this offseason',
    'recap.noRetirements': 'No retirements this offseason.',

    // ---- Summary ----
    'summary.dynasty': 'Dynasty mode',
    'summary.seasonSummary': 'Season Summary',
    'summary.seasons': 'seasons',
    'summary.championships': 'championships',
    'summary.seasonHistory': 'Season History',
    'summary.awards': 'Awards',
    'summary.roster': 'Roster',
    'summary.teamLeaders': 'Team Leaders',
    'summary.generated': 'generated',

    // ---- Resume ----
    'resume.draft': 'Draft',
    'resume.lineup': 'Set your starting 5',
    'resume.freeagency': 'Offseason free agency',
    'resume.preseason': 'Ready for the regular season',
    'resume.midseason': 'Mid-season',
    'resume.season': 'Season complete',
    'resume.playoffs': 'Playoffs',
    'resume.finished': 'Season over — view result',

    // ---- Matchup ----
    'matchup.desc': 'Build two 10-man teams, set 5 starters each, then simulate head-to-head.',
    'matchup.mode': 'Mode',
    'matchup.regular': 'Regular Season',
    'matchup.playoff': 'Playoff (starters/top-8 favoured)',
    'matchup.times': 'Times (max 100)',
    'matchup.simulate': 'Simulate',

    // ---- Library ----
    'lib.position': 'Position',
    'lib.all': 'All',
    'lib.search': 'Search',
    'lib.searchPlaceholder': 'Player name…',
    'lib.sortHint': 'Click a column header to sort.',
    'lib.header.name': 'Name',
    'lib.header.pos': 'Pos',
    'lib.header.ovr': 'OVR',
    'lib.header.age': 'Age',

    // ---- Save ----
    'save.export': '⬇ Export',
    'save.import': '⬆ Import',
    'save.sessionId': 'Session ID:',
    'save.copy': 'Copy ID',
    'save.switch': 'Switch:',
    'save.switchPlaceholder': 'paste session ID',
    'save.switchBtn': 'Switch',

    // ---- Standings ----
    'standings.east': 'Eastern Conference',
    'standings.west': 'Western Conference',

    // ---- Misc ----
    'misc.loading': 'Loading…',
    'misc.noHistory': 'No history yet.',
    'misc.noTrophies': 'No trophies yet. Win a championship!',
    'misc.noHof': 'No legends yet.',
    'misc.noArchive': 'No seasons saved yet.',
    'misc.sessionCopied': 'Session ID copied.',
    'misc.copyFailed': 'Copy failed — select and copy it manually.',
    'misc.pasteFirst': 'Paste a session ID first.',
    'misc.pts': 'pts',
    'misc.reb': 'reb',
    'misc.ast': 'ast',
    'misc.games': 'games',
    'misc.good': 'win',
    'misc.bad': 'loss',
    'misc.savesNone': 'No players drafted yet.',
  },

  zh: {
    'brand.title': '冠军之路',
    'brand.tagline': 'NBA 阵容构建模拟',
    'nav.home': '首页',
    'home.newRun': '开始新游戏',
    'home.newRun.desc': '选择球队、组建阵容、争夺总冠军。',
    'home.save': '存档与备份',
    'home.save.desc': '导出、导入或切换存档。',
    'home.library': '球员库',
    'home.library.desc': '搜索并排序全部球员的评分、数据和位置。',
    'home.matchup': '模拟对战',
    'home.matchup.desc': '组建两支球队进行模拟对决。',
    'home.trophy': '🏆 奖杯陈列室',
    'home.hof': '🏅 名人堂',
    'home.manageSaves': '管理存档…',
    'home.continue': '继续上次游戏',
    'home.continueBtn': '继续',
    'form.gameMode': '游戏模式',
    'form.normal': '普通',
    'form.normalHint': '（2025-26赛季）',
    'form.dynasty': '王朝',
    'form.dynastyHint': '（最多10个赛季）',
    'form.teamName': '自定义队名',
    'form.teamNameHint': '（选填）',
    'form.teamName.placeholder': '例如：重建者',
    'form.replaceTeam': '替换球队（决定分区）',
    'form.draftMode': '选秀模式',
    'form.open': '公开',
    'form.blind': '盲选',
    'form.difficulty': '难度',
    'form.normalDiff': '普通',
    'form.hard': '困难',
    'form.hardHint': '（$400M 工资帽）',
    'form.startDraft': '开始选秀',
    'form.archive': '赛季存档',
    'step.draft': '选秀',
    'step.lineup': '阵容',
    'step.season': '赛季',
    'step.playoffs': '季后赛',
    'step.result': '结果',
    'draft.title': '选秀',
    'draft.rookieTitle': '新秀选秀',
    'draft.desc': '每轮从5名球员中选1人,直到满10人。',
    'draft.reroll': '重新抽取',
    'draft.picked': '已选',
    'draft.need': '需要',
    'draft.pick': '选择',
    'draft.bigBoard': '选秀大会',
    'draft.yourPick': '你的选秀顺位',
    'draft.picksSoFar': '选秀进行中',
    'draft.pass': '弃权(跳过选秀)',
    'fa.title': '休赛期自由市场',
    'fa.desc': '释放球员腾出名额,然后签约自由球员。或者直接前往阵容设置。',
    'fa.done': '完成 — 前往阵容设置',
    'fa.release': '释放',
    'fa.sign': '签约',
    'fa.contract': '合同',
    'fa.years': '年',
    'fa.salary': '薪资',
    'fa.needs': '需求',
    'fa.refresh': '刷新市场',
    'fa.signings': '已签约',
    'lineup.title': '设置首发五人',
    'lineup.desc': '为每个位置分配一名球员。错位球员会受到评分惩罚。',
    'lineup.strength': '球队实力',
    'lineup.updates': '调整首发时实时更新',
    'lineup.confirm': '确认阵容',
    'season.title': '常规赛',
    'season.simulate': '模拟82场赛季',
    'season.midseason': '赛季中段休息',
    'season.midseasonHelp': '你现在可以调整阵容、进行交易,然后模拟下半赛季。',
    'season.adjustLineup': '🎯 调整阵容',
    'season.tradeWindow': '🔄 交易窗口',
    'season.simulateSecond': '▶ 模拟下半赛季',
    'season.averages': '球队场均数据',
    'season.firstHalf': '上半赛季场均',
    'season.afterGames': '第',
    'season.form': '赛季状态',
    'season.awards': '常规赛奖项',
    'season.mvp': '🏆 MVP',
    'season.dpoy': '🛡️ 最佳防守',
    'season.sixthMan': '🔥 最佳第六人',
    'season.allNba': '🌟 最佳阵容一阵',
    'season.missedPlayoffs': '你未能进入季后赛。',
    'season.backHome': '返回首页',
    'season.toPlayoffs': '继续季后赛',
    'trade.pointsRemaining': '剩余交易点数',
    'trade.pointsThis': '本赛季可用',
    'trade.rules': '规则：1换1消耗1点 · 2换2消耗2点 · 3换3消耗3点。每赛季共3点。',
    'trade.propose': '提案',
    'trade.shop': '挂牌求购',
    'trade.incoming': '收到报价',
    'trade.yourPlayers': '你的球员（1-3人）',
    'trade.pickSame': '球员（选同等数量）',
    'trade.proposeBtn': '提出交易',
    'trade.shopBtn': '获取报价',
    'trade.acceptBtn': '接受',
    'trade.pickPlayers': '挂牌这些球员（1-3人）',
    'trade.leagueLog': '联盟交易记录',
    'trade.accepted': '交易达成',
    'trade.rejected': '交易被拒绝',
    'trade.needSame': '请选择同等数量（1-3人）。',
    'playoffs.title': '季后赛',
    'playoffs.settingUp': '正在设置对阵…',
    'playoffs.bracket': '季后赛对阵',
    'playoffs.round': '第',
    'playoffs.simulateRound': '模拟第',
    'playoffs.roundResult': '轮结果',
    'playoffs.def': '击败',
    'playoffs.youWon': '你赢了',
    'playoffs.youLost': '你输了',
    'playoffs.mvp': '🏅 系列赛MVP',
    'playoffs.seriesRosters': '双方阵容（各10人）',
    'playoffs.playerAverages': '球员场均（系列赛）',
    'playoffs.wonChampionship': '赢得了总冠军！',
    'playoffs.seeResult': '查看结果',
    'playoffs.eliminated': '你在第',
    'playoffs.eliminatedEnd': '轮被淘汰。季后赛继续进行。',
    'result.title': '赛季结果',
    'result.champions': '总冠军！',
    'result.eliminated': '在第',
    'result.eliminatedRound': '轮被淘汰',
    'result.wonTitle': '赢得了NBA总决赛。',
    'result.dynastyMaterial': '王朝之师。',
    'result.rebuild': '你的征程结束了。重建再战。',
    'result.otherChampOther': '赢得了总冠军',
    'result.championships': '冠军次数',
    'result.awardsWon': '获奖次数',
    'result.starters': '首发',
    'result.bench': '替补',
    'result.topScorers': '得分王',
    'result.teamLeaders': '球队领袖',
    'result.nextSeason': '下赛季',
    'result.dynastyComplete': '🏆 王朝完成 —',
    'result.seasons': '个赛季。',
    'result.printSummary': '🖨️ 保存/打印摘要',
    'result.backHome': '返回首页',
    'result.dynastyHistory': '王朝历史',
    'history.season': '赛季',
    'history.record': '战绩',
    'history.champion': '冠军',
    'history.mvp': 'MVP',
    'history.result': '结果',
    'history.championLabel': '🏆 冠军',
    'history.missedPlayoffs': '未进季后赛',
    'history.eliminated': '被淘汰 R',
    'history.playoffs': '季后赛',
    'recap.title': '休赛期回顾',
    'recap.continue': '继续',
    'recap.champion': '🏆 总冠军',
    'recap.mvp': '🌟 常规赛MVP',
    'recap.retired': '本休赛期退役球员',
    'recap.noRetirements': '本休赛期无球员退役。',
    'summary.dynasty': '王朝模式',
    'summary.seasonSummary': '赛季总结',
    'summary.seasons': '个赛季',
    'summary.championships': '次冠军',
    'summary.seasonHistory': '赛季历史',
    'summary.awards': '奖项',
    'summary.roster': '阵容',
    'summary.teamLeaders': '球队领袖',
    'summary.generated': '生成于',
    'resume.draft': '选秀中',
    'resume.lineup': '设置首发五人',
    'resume.freeagency': '休赛期自由市场',
    'resume.preseason': '准备开始赛季',
    'resume.midseason': '赛季中段',
    'resume.season': '赛季完成',
    'resume.playoffs': '季后赛',
    'resume.finished': '赛季结束 — 查看结果',
    'matchup.desc': '组建两支10人球队,各设5名首发,然后模拟对决。',
    'matchup.mode': '模式',
    'matchup.regular': '常规赛',
    'matchup.playoff': '季后赛（首发/前8人加权）',
    'matchup.times': '次数（最多100）',
    'matchup.simulate': '模拟',
    'lib.position': '位置',
    'lib.all': '全部',
    'lib.search': '搜索',
    'lib.searchPlaceholder': '球员名字…',
    'lib.sortHint': '点击列标题排序。',
    'lib.header.name': '名字',
    'lib.header.pos': '位置',
    'lib.header.ovr': '能力值',
    'lib.header.age': '年龄',
    'save.export': '⬇ 导出存档',
    'save.import': '⬆ 导入存档',
    'save.sessionId': 'Session ID：',
    'save.copy': '复制',
    'save.switch': '切换：',
    'save.switchPlaceholder': '粘贴Session ID',
    'save.switchBtn': '切换',
    'standings.east': '东部',
    'standings.west': '西部',
    'misc.loading': '加载中…',
    'misc.noHistory': '暂无历史记录。',
    'misc.noTrophies': '暂无奖杯。赢得一座总冠军！',
    'misc.noHof': '暂无名人堂成员。',
    'misc.noArchive': '暂无赛季存档。',
    'misc.sessionCopied': 'Session ID 已复制。',
    'misc.copyFailed': '复制失败 — 请手动选择并复制。',
    'misc.pasteFirst': '请先粘贴Session ID。',
    'misc.pts': '分',
    'misc.reb': '篮板',
    'misc.ast': '助攻',
    'misc.games': '场',
    'misc.good': '连胜',
    'misc.bad': '连败',
    'misc.savesNone': '暂无已选球员。',
  },
};

// Current language (persisted in localStorage)
let currentLang = localStorage.getItem('cr_lang') || 'zh';
const t = (key) => (LANG[currentLang] && LANG[currentLang][key]) || (LANG.en[key]) || key;

// Apply translations to all elements with data-i18n attribute
function applyI18n() {
  document.querySelectorAll('[data-i18n]').forEach((el) => {
    const key = el.getAttribute('data-i18n');
    const val = t(key);
    if (val) el.textContent = val;
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach((el) => {
    const key = el.getAttribute('data-i18n-placeholder');
    const val = t(key);
    if (val) el.placeholder = val;
  });
  // Update <html lang>
  document.documentElement.lang = currentLang === 'zh' ? 'zh-CN' : 'en';
  // Update title
  document.title = t('brand.title');
  // Update lang switcher button text
  const btn = document.getElementById('lang-btn');
  if (btn) btn.textContent = currentLang === 'zh' ? 'EN' : '中';
}

function switchLang() {
  currentLang = currentLang === 'zh' ? 'en' : 'zh';
  localStorage.setItem('cr_lang', currentLang);
  applyI18n();
}
