const fs = require('fs');

const norm = s => (s || '')
  .toLowerCase()
  .replace(/&#?[a-z0-9]+;/gi, '')
  .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
  .replace(/[^a-z0-9 ]/g, '')
  .replace(/\b(jr|sr|ii|iii|iv)\b/g, '')
  .replace(/\s+/g, ' ').trim();

const txt = fs.readFileSync('C:/Users/yaohr/championship-run/database/2k27_players.txt', 'utf8');
const k2 = txt.trim().split('\n').map(l => l.split('\t')[0].trim());

const base = `
Luka Doncic
Shai Gilgeous-Alexander
Anthony Edwards
Jaylen Brown
Tyrese Maxey
Kawhi Leonard
Donovan Mitchell
Nikola Jokic
Giannis Antetokounmpo
Joel Embiid
Lauri Markkanen
Stephen Curry
Devin Booker
Jalen Brunson
Kevin Durant
Jamal Murray
Victor Wembanyama
Deni Avdija
Michael Porter Jr.
Pascal Siakam
Cade Cunningham
James Harden
Keyonte George
Austin Reaves
Jalen Johnson
Paolo Banchero
Jayson Tatum
Norman Powell
Brandon Ingram
Trey Murphy III
Julius Randle
Cooper Flagg
Zion Williamson
LeBron James
Nickeil Alexander-Walker
Shaedon Sharpe
Franz Wagner
Tyler Herro
Anthony Davis
Alperen Sengun
Dillon Brooks
Brandon Miller
Bam Adebayo
LaMelo Ball
Desmond Bane
Karl-Anthony Towns
Jimmy Butler
Ty Jerome
Jalen Duren
Ja Morant
Jaren Jackson Jr.
RJ Barrett
Zach LaVine
Darius Garland
CJ McCollum
De'Aaron Fox
Jerami Grant
Kon Knueppel
DeMar DeRozan
Amen Thompson
Evan Mobley
Scottie Barnes
Trae Young
Jalen Green
Saddiq Bey
Bennedict Mathurin
Coby White
Kevin Porter Jr.
Paul George
Ryan Rollins
Miles Bridges
Chet Holmgren
Jalen Williams
Josh Giddey
Payton Pritchard
Andrew Nembhard
Kristaps Porzingis
OG Anunoby
Stephon Castle
Dejounte Murray
Grayson Allen
Derrick White
Immanuel Quickley
Matas Buzelis
Jrue Holiday
Alex Sarr
Dariq Whitehead
Aaron Gordon
VJ Edgecombe
Domantas Sabonis
Jabari Smith Jr.
Collin Sexton
Jarrett Allen
Jaime Jaquez Jr.
Andrew Wiggins
Naji Marshall
Onyeka Okongwu
Russell Westbrook
Nikola Vucevic
Anthony Black
Kennedy Chandler
Brice Sensabaugh
Ayo Dosunmu
Kyshawn George
Jaden McDaniels
Peyton Watson
Mikal Bridges
Walker Kessler
Anfernee Simons
Jeremiah Fears
Cormac Ryan
Scoot Henderson
P.J. Washington
Ivica Zubac
Tre Jones
Kelly Oubre Jr.
Santi Aldama
Keegan Murray
Devin Vassell
Ace Bailey
Aaron Nesmith
Brandin Podziemski
Jalen Suggs
De'Andre Hunter
Bobby Portis
John Collins
Cedric Coward
Zach Edey
Ajay Mitchell
Naz Reid
Cam Thomas
Tim Hardaway Jr.
Reed Sheppard
Toumani Camara
Quentin Grimes
Jordan Poole
Tobias Harris
Keldon Johnson
Jaylon Tyson
Kyle Kuzma
Brandon Williams
Sam Merrill
Collin Gillespie
Deandre Ayton
GG Jackson II
Malik Monk
Maxime Raynaud
Jaylen Wells
Max Christie
Noah Clowney
De'Anthony Melton
Jonathan Kuminga
Donte DiVincenzo
Cameron Johnson
Tre Johnson
Duncan Robinson
Donovan Clingan
Moses Moody
Christian Braun
Josh Hart
Miles McBride
Tristen Newton
Dyson Daniels
Blake Hinson
Myles Turner
Wendell Carter Jr.
Dylan Harper
Julian Reese
Nic Claxton
Isaiah Collier
Bilal Coulibaly
Derik Queen
Klay Thompson
Mark Williams
Obi Toppin
Jarace Walker
Rui Hachimura
Kyle Filipowski
Pelle Larsson
Scotty Pippen Jr.
Sandro Mamukelashvili
Max Strus
Julian Champagnie
Isaiah Joe
Cam Spencer
Kel'el Ware
Alondes Williams
Rudy Gobert
Jusuf Nurkic
Dennis Schroder
Tyler Burton
Daeqwon Plowden
Bub Carrington
Jakob Poeltl
Jock Landale
Marvin Bagley III
Tari Eason
Adama-Alpha Bal
A.J. Green
Caleb Love
Lucas Williamson
Egor Demin
DaQuan Jeffries
Will Riley
Khris Middleton
Neemias Queta
D'Angelo Russell
Jalen Smith
Ziaire Williams
Precious Achiuwa
Derrick Jones Jr.
Kevin Huerter
Jordan Miller
Toby Okani
Olivier-Maxence Prosper
Isaiah Stewart
Harrison Barnes
Tristan Da Silva
Ausar Thompson
Royce O'Neale
Zach Collins
Micah Potter
Javon Small
Zaccharie Risacher
Daniel Gafford
Jay Huff
T.J. McConnell
Svi Mykhailiuk
Aaron Wiggins
Daniss Jenkins
Davion Mitchell
Isaac Okoro
Landry Shamet
Marcus Smart
Jaden Hardy
Isaiah Hartenstein
Sam Hauser
Corey Kispert
Taurean Prince
Gui Santos
Cam Whitmore
Quenton Jackson
Tristan Vukcevic
Devin Carter
Herbert Jones
Nolan Traore
Danny Wolf
John Poulakidas
Payton Sandfort
Cody Williams
Justin Champagnie
Jordan Goodwin
Day'Ron Sharpe
Jonas Valanciunas
Jordan Clarkson
Nique Clifford
Cason Wallace
Jaden Ivey
Vit Krejci
Simone Fontecchio
Bones Hyland
Brook Lopez
Collin Murray-Boyles
Luke Kennard
Kentavious Caldwell-Pope
Draymond Green
Jared McCain
Luguentz Dort
Al Horford
Josh Oduro
Kadary Richmond
Malachi Smith
Bradley Beal
LJ Cryer
Ron Holland
Chaney Johnson
Jake LaRavia
Sharife Cooper
Luka Garza
Bez Mbeng
Bryce McGowens
Gary Trent Jr.
Mouhamadou Gueye
DeJon Jarreau
David Roddy
Tre Scott
Nate Williams
Bruce Brown
Moussa Diabate
Tyson Etienne
Leonard Miller
Walter Clayton
Paul Reed
Oscar Tshiebwe
Dominick Barlow
Quinten Post
Ousmane Dieng
Buddy Hield
Ryan Kalkbrenner
Vince Williams Jr.
Jaxson Hayes
Gary Payton II
Ben Saraf
Ja'Kobe Walter
Josh Minott
Taylor Hendricks
Jose Alvarado
Bogdan Bogdanovic
Caris LeVert
Cameron Payne
Jamir Watkins
Kris Dunn
Nikola Jovic
Kobe Sanders
Jalen Slawson
Terance Mann
Pat Spencer
Julian Strawther
Jaylin Williams
Leaky Black
Seth Curry
Ben Sheppard
Lawson Lovering
Ethan Thompson
Grant Williams
Patrick Williams
Javonte Green
Moritz Wagner
MarJon Beauchamp
Elijah Harkless
Keon Ellis
Isaiah Jackson
Cole Anthony
Kevin Love
Robert Williams
Ryan Nembhard
Jamal Shead
Oso Ighodaro
Luke Kornet
Drake Powell
Trendon Watford
Kenrich Williams
Jevon Carter
Andre Drummond
Will Richard
Jalen Wilson
Rob Dillingham
Tyrese Martin
Kyle Anderson
Thomas Bryant
Alex Caruso
Kasparas Jakucionis
Jahmai Mashack
Nick Smith Jr.
Mac McClung
Gradey Dick
Justin Edwards
Hayden Gray
Tidjane Salaun
Goga Bitadze
Charles Bassey
Kobe Brown
Nick Richards
Steven Adams
Branden Carlson
Ryan Dunn
Anthony Gill
Kris Murray
Matisse Thybulle
Nae'Qwan Tomlin
Dean Wade
Jamaree Bouyea
E.J. Liddell
Karlo Matkovic
Doug McDermott
Yves Missi
Mitchell Robinson
Guerschon Yabusele
Terrence Shannon Jr.
Dru Smith
Eric Gordon
Killian Hayes
Aaron Holiday
Jett Howard
Spencer Jones
Tre Mann
Baylor Scheierman
Jamal Cain
Dylan Cardwell
Haywood Highsmith
Sion James
Pete Nance
Tyrese Proctor
Jordan Walsh
Rayan Rupert
Trey Alexander
Drew Eubanks
Andersson Garcia
Garrison Mathews
Asa Newell
Jalen Pickett
Marcus Sasser
Nikola Topic
`.trim().split('\n').map(s => s.trim());

const epm = `
Victor Wembanyama
Nikola Jokic
Kawhi Leonard
Shai Gilgeous-Alexander
Giannis Antetokounmpo
Luka Doncic
LaMelo Ball
Ty Jerome
Karl-Anthony Towns
Chet Holmgren
Jimmy Butler III
Stephen Curry
Jayson Tatum
Joel Embiid
Bam Adebayo
Franz Wagner
Tyrese Haliburton
Jarrett Allen
Donovan Mitchell
Cade Cunningham
Lauri Markkanen
Kyrie Irving
Paul Reed
Dyson Daniels
Ausar Thompson
Isaiah Hartenstein
Scottie Barnes
Ajay Mitchell
Neemias Queta
Amen Thompson
Jalen Williams
Devin Booker
Jalen Brunson
Derrick White
Kevin Durant
Rudy Gobert
Alex Caruso
Donovan Clingan
Kon Knueppel
Pascal Siakam
Jamal Murray
Brandon Miller
Payton Pritchard
Jrue Holiday
OG Anunoby
Darius Garland
Michael Porter Jr.
Austin Reaves
Kristaps Porzingis
De'Aaron Fox
Dylan Harper
Moses Moody
LeBron James
Damian Lillard
Stephon Castle
Grayson Allen
Coby White
Jalen Duren
Cason Wallace
Tyrese Maxey
Norman Powell
Ja Morant
Julian Champagnie
Tobias Harris
Mitchell Robinson
Deni Avdija
Desmond Bane
Fred VanVleet
Trae Young
Marcus Smart
Collin Gillespie
Aaron Gordon
Nickeil Alexander-Walker
Anthony Davis
Donte DiVincenzo
Zach Edey
Paolo Banchero
Anthony Edwards
Collin Murray-Boyles
Moussa Diabate
Jalen Johnson
Devin Vassell
Immanuel Quickley
Paul George
Evan Mobley
Trey Murphy III
Jaylen Brown
Dejounte Murray
RJ Barrett
Sam Hauser
James Harden
Jaren Jackson Jr.
Luka Garza
Day'Ron Sharpe
VJ Edgecombe
Cedric Coward
Gui Santos
Jordan Goodwin
Isaiah Joe
Domantas Sabonis
Cooper Flagg
Tyler Herro
Wendell Carter Jr.
Jaden McDaniels
Jalen Suggs
Miles McBride
Sandro Mamukelashvili
Josh Hart
Tari Eason
Obi Toppin
Jalen Smith
Andrew Nembhard
Dillon Brooks
Tre Jones
Cameron Johnson
Ivica Zubac
Saddiq Bey
Mikal Bridges
Scotty Pippen Jr.
Jose Alvarado
Jakob Poeltl
De'Anthony Melton
Gary Payton II
Julius Randle
Alperen Sengun
CJ McCollum
Zion Williamson
Ryan Rollins
Brandin Podziemski
Javonte Green
Robert Williams III
Derrick Jones Jr.
Jabari Smith Jr.
Naji Marshall
Davion Mitchell
Kevin Porter Jr.
Duncan Robinson
Jaylin Williams
Brook Lopez
Herbert Jones
Dereck Lively II
Walker Kessler
Pelle Larsson
Peyton Watson
Toumani Camara
Al Horford
Oso Ighodaro
Moritz Wagner
Goga Bitadze
Jalen Green
Onyeka Okongwu
Josh Giddey
Nic Claxton
Kel'el Ware
Ron Harper Jr.
T.J. McConnell
Simone Fontecchio
Baylor Scheierman
Aaron Nesmith
Kevin Huerter
Jusuf Nurkic
Dean Wade
Daniel Gafford
Sam Merrill
Quinten Post
Christian Braun
Steven Adams
Naz Reid
Brandon Clarke
Daniss Jenkins
Jamal Shead
Cam Spencer
Miles Bridges
Cameron Payne
Chris Boucher
Josh Minott
Javon Small
Kris Dunn
Luke Kornet
Kyle Filipowski
Jaylen Wells
Justin Champagnie
Reed Sheppard
Lonzo Ball
Svi Mykhailiuk
Elijah Harkless
Myron Gardner
Santi Aldama
Nikola Vucevic
Jordan Walsh
Keegan Murray
Matisse Thybulle
Bones Hyland
Devin Carter
Grant Williams
Matas Buzelis
Marcus Sasser
D'Angelo Russell
Vince Williams Jr.
Anfernee Simons
DeMar DeRozan
Jonathan Kuminga
Ja'Kobe Walter
Mike Conley
Jonas Valanciunas
Mark Williams
Mouhamed Gueye
Ronald Holland II
Leonard Miller
AJ Green
P.J. Washington
Jaylon Tyson
Olivier-Maxence Prosper
Jamir Watkins
Dru Smith
Bogdan Bogdanovic
Alex Sarr
Kyshawn George
Sion James
Kentavious Caldwell-Pope
Zach LaVine
Josh Okogie
Quenton Jackson
Kevin Love
Jonathan Isaac
Andrew Wiggins
Myles Turner
Klay Thompson
Malik Monk
Jaxson Hayes
Brandon Williams
Rui Hachimura
Keldon Johnson
Shaedon Sharpe
Keyonte George
Brandon Ingram
Jock Landale
Kasparas Jakucionis
Clint Capela
John Collins
De'Andre Hunter
Nae'Qwan Tomlin
Jaime Jaquez Jr.
Precious Achiuwa
Bennedict Mathurin
Kobe Sanders
Collin Sexton
Jeremiah Fears
Deandre Ayton
Bradley Beal
Bobby Portis
Tyrese Proctor
Buddy Boeheim
Kevon Looney
Kelly Oubre Jr.
Jay Huff
Anthony Black
Ayo Dosunmu
Ziaire Williams
GG Jackson
Egor Demin
Ryan Nembhard
Landry Shamet
Luguentz Dort
Aaron Holiday
Harrison Barnes
Ethan Thompson
Hugo Gonzalez
Georges Niang
Jaylen Clark
Cam Thomas
Thomas Bryant
Tim Hardaway Jr.
Isaiah Jackson
Jared McCain
Josh Green
Jerami Grant
Nikola Jovic
Ryan Kalkbrenner
Kenrich Williams
LJ Cryer
Jordan Miller
Micah Potter
Andre Drummond
Tolu Smith
Brice Sensabaugh
Guerschon Yabusele
DaRon Holmes II
Koby Brea
Jake LaRavia
Dwight Powell
Isaac Okoro
Max Strus
Dorian Finney-Smith
Tristan da Silva
Jordan Poole
Aaron Wiggins
Tristan Vukcevic
Buddy Hield
Zach Collins
Russell Westbrook
Luke Kennard
Bilal Coulibaly
Chucky Hepburn
Chaney Johnson
Dominick Barlow
JD Davison
DeJon Jarreau
John Konchar
Trevor Keels
Garrison Mathews
Draymond Green
Tyler Kolek
Max Christie
Johnny Furphy
Blake Hinson
Trayce Jackson-Davis
RayJ Dennis
Jamal Cain
Khris Middleton
Kris Murray
Marvin Bagley III
Quentin Grimes
Rasheer Fleming
Haywood Highsmith
Jamaree Bouyea
Dario Saric
Mark Sears
Oscar Tshiebwe
Nique Clifford
Terrence Shannon Jr.
Jarred Vanderbilt
Jackson Rowe
Tyler Burton
Monte Morris
Scoot Henderson
Asa Newell
Keon Ellis
Ryan Dunn
Gary Trent Jr.
Seth Curry
Bobi Klintman
PJ Hall
Taurean Prince
Branden Carlson
Kobe Bufkin
John Poulakidas
Chris Paul
Noah Clowney
Isaiah Stewart
Sean Pedulla
Keshad Johnson
Alex Antetokounmpo
Danny Wolf
Cam Whitmore
Caleb Love
Dante Exum
Keaton Wallace
Jordan Clarkson
Taylor Hendricks
A.J. Lawson
David Jones Garcia
Dylan Cardwell
Malachi Smith
Karlo Matkovic
Tre Johnson
Tristen Newton
Kelly Olynyk
Jabari Walker
Ace Bailey
Jalen Pickett
Terance Mann
Daeqwon Plowden
Liam McNeeley
Caleb Houstan
Nicolas Batum
Will Richard
Corey Kispert
Tyler Smith
Chris Youngblood
Vit Krejci
Adem Bona
Caris LeVert
Kevon Harris
MarJon Beauchamp
Jules Bernard
Spencer Jones
Gradey Dick
Curtis Jones
Dennis Schroder
Pat Connaughton
Jaden Hardy
Johnny Juzang
Royce O'Neale
Jaden Springer
Orlando Robinson
Pat Spencer
Tosan Evbuomwan
Jaden Ivey
Kyle Anderson
Mac McClung
Carter Bryant
Micah Peavy
Julian Strawther
Craig Porter Jr.
Chaz Lanier
Mohamed Diawara
Killian Hayes
Jalen Slawson
Cormac Ryan
Lucas Williamson
Lachlan Olbrich
Noa Essengue
Bub Carrington
Yuki Kawamura
Duop Reath
Antonio Reeves
Lindy Waters III
Eric Gordon
Terry Rozier
Ochai Agbaji
Cam Christie
Alijah Martin
Colby Jones
Justin Edwards
Gabe Vincent
Joan Beringer
Malevy Leons
Tamar Bates
Hunter Tyson
Cody Martin
Sidy Cissoko
Grant Nelson
Drew Peterson
KJ Simpson
Jae'Sean Tate
Kennedy Chandler
Jevon Carter
Thomas Sorber
Dalano Banton
Maxime Raynaud
Garrett Temple
Adama Bal
David Roddy
Ousmane Dieng
Ben Sheppard
Bryce McGowens
Zaccharie Risacher
Miles Kelly
Andersson Garcia
Julian Reese
Trevon Scott
Kadary Richmond
Jase Richardson
John Tonje
Kyle Lowry
Nate Williams
Tyrese Martin
Cole Anthony
DeAndre Jordan
Kyle Kuzma
Colin Castleton
Chris Livingston
Larry Nance Jr.
Moussa Cisse
Jordan McLaughlin
Hayden Gray
Pacome Dadiet
Nikola Djurisic
Max Shulga
Jayson Kent
Kobe Brown
N'Faly Dante
Jett Howard
Xavier Tillman
Kyle Mangas
Mo Bamba
Zeke Nnaji
Stanley Umude
Eli John Ndiaye
Kevin McCullar Jr.
Alex Toohey
Charles Bassey
Derik Queen
Yanic Konan Niederhauser
Luke Travers
Julian Phillips
Caleb Martin
Malik Williams
Jericho Sims
Tony Bradley
Patrick Baldwin Jr.
Gabe McGlothan
Norchad Omier
Javonte Cooke
Jacob Toppin
Will Riley
Amir Coffey
Riley Minix
Tidjane Salaun
Jeremiah Robinson-Earl
Tyus Jones
Dalen Terry
Tristan Enaruna
Lawson Lovering
Noah Penda
TyTy Washington Jr.
E.J. Liddell
Alex Morales
Jarace Walker
Walter Clayton Jr.
Jeremy Sochan
Khaman Maluach
Bruce Brown
Tre Mann
Jahmir Young
Yves Missi
Gary Harris
Doug McDermott
Pete Nance
Tyson Etienne
Nikola Topic
Christian Koloko
Nolan Traore
Tyreke Key
Emanuel Miller
Trentyn Flowers
Joe Ingles
Omer Yurtseven
Darius Brown
Andre Jackson Jr.
Jalen Wilson
DaQuan Jeffries
Jeff Green
CJ Huntley
Trendon Watford
Jamison Battle
Ariel Hukporti
Isaiah Livers
Alondes Williams
Isaiah Crawford
Taelon Peter
Isaac Jones
Kam Jones
Isaiah Collier
Dalton Knecht
Amari Williams
Johni Broome
Bez Mbeng
Sharife Cooper
Isaiah Stevens
Jahmyl Telfort
Malaki Branham
Payton Sandfort
Drew Eubanks
Jonathan Mogbo
Toby Okani
Olivier Sarr
Josh Oduro
Dariq Whitehead
Taj Gibson
Wendell Moore Jr.
Drew Timme
Nick Richards
Rocco Zikarsky
Trey Alexander
Leaky Black
Mason Plumlee
Maxi Kleber
Zyon Pullin
Vladislav Goldin
Blake Wesley
Patrick Williams
Skal Labissiere
AJ Johnson
Cody Williams
Anthony Gill
Adou Thiero
Nick Smith Jr.
Drake Powell
Enrique Freeman
Hunter Sallis
Rob Dillingham
Dillon Jones
Hunter Dickinson
James Wiseman
Bronny James
Keshon Gilbert
Nigel Hayes-Davis
Thanasis Antetokounmpo
Chris Manon
Markelle Fultz
Brooks Barnhizer
Yang Hansen
Ben Saraf
Jordan Hawkins
Mouhamadou Gueye
Harrison Ingram
Rayan Rupert
Jahmai Mashack
Trey Jemison
Bismack Biyombo
`.trim().split('\n').map(s => s.trim());

const bset = new Set(base.map(norm));
const eset = new Set(epm.map(norm));
const kset = new Set(k2.map(norm));

const k2NotBase = k2.filter(n => !bset.has(norm(n)));
const k2NotEpm = k2.filter(n => !eset.has(norm(n)));
const baseNotK2 = [...new Set(base.filter(n => !kset.has(norm(n))))];
const epmNotK2 = [...new Set(epm.filter(n => !kset.has(norm(n))))];

console.log('2K total:', k2.length);
console.log('base total:', base.length, '(incl. dup rows)');
console.log('epm total:', epm.length);
console.log('');
console.log('=== 2K players NOT in base stats (' + k2NotBase.length + ') ===');
console.log(k2NotBase.join('\n'));
console.log('');
console.log('=== 2K players NOT in EPM (' + k2NotEpm.length + ') ===');
console.log(k2NotEpm.join('\n'));
console.log('');
console.log('=== base players NOT in 2K (' + baseNotK2.length + ') ===');
console.log(baseNotK2.join('\n'));
console.log('');
console.log('=== EPM players NOT in 2K (' + epmNotK2.length + ') ===');
console.log(epmNotK2.join('\n'));
